services:

  wordpress:
    container_name: wordpresscontainer
    image: wordpress
    restart: always
    ports:
      - 8222:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: Admin@123
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wordpress:/var/www/html

  db:
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin@123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
